site_name: Soil OI 资料库
repo_url: https://github.com/ASoyou/oilibrary/
theme:
  name: material
  palette:
    primary: grey
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  consent:
    title: Cookie 请求
    description: >- 
      我们使用 cookie 来识别您的重复访问和偏好以衡量我们文档的有效性以及用户找到他们正在搜索的内容。在您同意的情况下，您在帮助我们使我们的文档更好。
nav:
  - "欢迎" :
    - "关于本站" :
      - "简介" : "index.md"
      - "学术规范" : "rules.md"
  - "数学" :
    - "数论" :
      - "基础" : "math/number-theory/basic1.md"
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
